### ISSUE TITLE
Asking for help to reduce container window size.

### ISSUE THREAD

**Issue by eGax** [Captain4LK/SoftLK-tools#2]
I'm trying to tidy up the excess window size to take up less real estate for my personal use. So far I have modified `SLK_img2pixel/src/gui.c` lines 268 & 277

Line 268:   `preview = SLK_gui_window_create(386,1,260,286);`
Line 277:   `settings = SLK_gui_window_create(1,1,384,296);`

I have successfully gotten results I like:
![image](https://user-images.githubusercontent.com/9817245/125209360-2e85e300-e266-11eb-8768-7f52ef712f36.png)
Could you please point me to the bit of code that defines the overall window container size? I haven't been able to find it. I want to make it smaller to fit around the Settings & Preview windows tightly and tidy up all the wasted space. Thanks!

**Comment by Captain4LK** [comment]
The SLK_setup(); call in main.c (currently l. 37) defines the window dimensions:

``SLK_setup(800,500,4,"SLK_img2pixel",0,SLK_WINDOW_MAX,1);``;
prototype: ``void SLK_setup(int width, int height, int layer_num, const char *title, int fullscreen, int scale, int resizable);``

The width and height parameters define the window width, but you most likely want to change the scale parameter (defines by what factor the pixel should be scaled, currently SLK_WINDOW_MAX) to something different too, since SLK_WINDOW_MAX tells SoftLK-lib to scale the pixels by the highest factor possible. On a 1080p screen it defaults to 2, on a 4k screen to 4.

If you additionally want the window to not be resizable you need to set resizable parameter to 0 and second parameter of the ``   SLK_layer_set_dynamic(2,1);`` (currently main.c:61) function call to 0.

**Comment by eGax** [comment]
OK, Say I don't want the pixels to be scaled as they are with `SLK_WINDOW_MAX`, what can I change it to? I want the Settings and Preview windows to remain the size they are as you have them by default. I'm only looking to shrink the SLK_img2pixel window they're inside. I have looked through the lib and img2pixel src and I can't find/figure it out.

I appreciate your comments here. I love using your img2pixel and although I'm not a coder looking at the code it isn't bad to read. Just having a little fun while changing a few things to suit me better.

**Comment by Captain4LK** [comment]
That depends on your screen resolution.
If the SLK_WINDOW_MAX flag is passed to SLK_setup, SoftLK-lib calculates the pixel scale by dividing the display resolution by  the window width/height , so if you want it to stay the same after changing the window dimensions you'll need to calculate it yourself (divide your x resolution by 800 and your y resolution by 500, round down and choose the smaller of the two values). As I said before on an 1080p screen this results in a scale value of 2. Then just replace SLK_WINDOW_MAX by this value.
I know its a bit messy, but I need to somehow make the window of img2pixel not be too small or too big on different screen resolutions.

Nice to hear that my code is at least readable, I spent some time cleaning it up, but the initial versions of both the gui framework and img2pixel were quite rushed.

**Comment by eGax** [comment]
I finally figured it out by replacing `SLK_WINDOW_MAX` with `2` and adjust x,y to match my changes and screen resolution. Looks good for me @ 1080 or my 1440 monitors.
```   SLK_setup(648,300,4,"SLK_img2pixel",0,2,1);```
![image](https://user-images.githubusercontent.com/9817245/125526763-68eae2cd-46b2-48da-88a6-ddf6134bde8e.png)
Thank you again for the help.
